version: '3'
services:
    glm-api:
        image: devilyouwei/glm-api-simple:latest
        container_name: glm-api
        ports:
            - 8100:8100
        environment:
            - CUDA_VISIBLE_DEVICES=all
        volumes:
            - ./model:/app/model
